run:
  skip-dirs:
    - .tmp
    - vendor

linters:
  disable-all: true
  enable:
    # - errcheck
    - gocritic
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - stylecheck
    - typecheck
    - unused

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true

issues:
  exclude-rules:
    - linters: [stylecheck]
      text: "ST1005:"
