language: go
go:
  - "1.11"
  - "1.12"
  - "1.13"
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.20.0
script:
  - golangci-lint run
  - go build
